### PR TITLE
Adding Dockerfile for automated builds

### LINKED ISSUE #104: Docker Hub wizzy version critically out of date
Using latest wizzy docker image and Grafana 4 I consistently experience that copying rows or panels results in the panel ids staying the same.

Having multiple panel ids causes erratic behavior in Grafana, including:

- Random display dropout
  - Upon dashboard load, once a given panel id loads the other matching panel id's space remains blank. Upon editing it in any way it restores itself, but sometimes to the other panel's configuration. See next issue:
- Editing one panel id modifies the first matching panel id.
  - Copy a row to the end of a chart, appending the copy basically. Edit the bottom appended chart. Save and refresh. Notice the first chart displays the new name.

This can be remedied by Viewing JSON and manually correcting the panel ids. Upon importing the modified JSON the displays behave as expected.

I can understand cases where maintaining the panel id is desired, cross dashboards for example. Perhaps the user should be given the option to maintain or increment them. Or perhaps an easier way to re-number them?

Moving/copying panels requires the row to already exist, but there is no "create empty row" command. Worse, copying panels also exhibits this same behavior, when the row exists, otherwise it encounters an unhandled error at:

```
/usr/local/lib/node_modules/wizzy/src/components.js:150
				var destPanels = srcRows[destRowNumber-1].panels;
```

I am presuming that this was not the case prior to Grafana 4 and regressed at that time, either way I wanted to raise an issue. If I am doing something wrong please don't hesitate to let me know! :)

### PR DESCRIPTION
**Pull request by nielsole**
This allows us to easily build this project on every release.
fixes #104

### CODE REVIEW

**Comment by nielsole** [comment]
Simply select "Create" and then "create automated build" and select this repo. 

Afterwards go to build settings and click the '+' and select tag and save the changes. and now we have automated builds

**Comment by nielsole** [comment]
Thank you for merging. Please also update the docker hub image https://hub.docker.com/r/utkarshcmu/wizzy/ by following the instructions above. You might have to delete the dockerhub image first.
Cheers

**Comment by r4j4h** [comment]
@nielsole Thanks so much for this!

**Comment by tinder-ubhatnagar** [comment]
Will update the docker image tonight. Thank you guys!

**Comment by utkarshcmu** [comment]
Will update the docker image tonight!

**Comment by utkarshcmu** [comment]
Updated the docker image.... can any of you please test that it works as it should? Thanks!

**Comment by nielsole** [comment]
Hey, that looks good, thanks. Whether the generation of tagged images is correct will only be observable, once you create a new git tag.

**Comment by Tim-Smyth** [comment]
No tagged version in https://hub.docker.com/r/utkarshcmu/wizzy/tags/ yet :(

**Comment by nielsole** [comment]
yes, but there also hasn't been a tagged commit yet since the changes. Could still be broken, but so far this is expected behaviour.

**Pull request merged**
