### PR TITLE
Pause alerts in grafana

### PR DESCRIPTION
**Pull request by Udayrakesh**

### CODE REVIEW

**Comment by utkarshcmu** [comment]
Will test this before 0.6.0 release!

**Comment by utkarshcmu** [comment]
@Udayrakesh  Can we unpause alerts too via CLI?

**Comment by Udayrakesh** [comment]
There is no api to unpause alerts.. @utkarshcmu

**Comment by utkarshcmu** [comment]
Or is it the same api to pause and unpause like toggling? Can you verify as I think we should have both pause and unpause functionality!

**Comment by Udayrakesh** [comment]
there was no option to toggle the pausing of alerts

**Comment by utkarshcmu** [comment]
Lets track this https://github.com/grafana/grafana/issues/6500 before merging this PR

**Comment by utkarshcmu** [comment]
Closing this PR!

**Pull request closed without merging**
