### PR TITLE
Enable Folder support

### PR DESCRIPTION
**Pull request by quadriq**
This PR bring the handling of the "Folder" feature in grafana v5.

Motivation: Folder is a great thing in grafana and it would be nice to support them. Also currently `wizzy list dashboard` and `wizzy import dashboards` handle folders as dashboards, so it is not clear what is what... to resolve this I create this PR

* `wizzy list dashboards`  - extending listing  with _dashboards_ and _folders_  parameters. 

* `wizzy import dashboards` would create folders in `dashboards` directory and import everything to it. "unfoldered" dashboards in grafana going to "dashboards/General" folder.

* `wizzy import dashboard General/mytestdash` - now it is needed to specify dashboard name together with folder path to export dashboard back into grafana. 

please review my changes and e.g merge them. I am open for discussion.

Thanks
Dmitry

### CODE REVIEW

**Comment by oleg-glushak** [comment]
For me import works well. But 'wizzy export dashboards' uploads all the dashboards to default folder.

**Comment by kyrias** [comment]
So the problem is that when exporting, the request sent to Grafana doesn't have `folderId` set.  So the question is whether we should try to fetch the current ID of the folder by that name from Grafana, or save it to the dashboard file when exporting?

Simplest would be to just save it when exporting, but then we don't know that the current folder with that ID is the same one, hm.  Too bad the API doesn't let you just give the folder title instead.

**Comment by bergerx** [comment]
@utkarshcmu did you you check this one?
I didn't see any recent comment or update from you recently, did you abandon the project?

**Comment by tinder-ubhatnagar** [comment]
I need to come back to this project, do not want to abandon it. Let me try to get this done this week or if someone can make a PR! :)

**Comment by tinder-ubhatnagar** [comment]
Actually its a PR, I am merging it now!

**Comment by kyrias** [comment]
Well, this PR doesn't actually work properly, so the feature isn't very useful until someone throws together a follow-up PR.

**Pull request merged**
